- name: Install Redis
  apt: pkg={{ item }} state=present
  with_items:
   - redis-server

# Set vm.overcommit_memory to safeguard background saves - see http://redis.io/topics/faq
- name: Set vm.overcommit_memory
  sysctl: name=vm.overcommit_memory value=1 state=present reload=yes