- name: Install elasticsearch.org apt key
  apt_key: url='http://packages.elasticsearch.org/GPG-KEY-elasticsearch' state=present

- name: Install elasticsearch.org apt repository
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.3/debian stable main' state=present

- name: Install Logstash
  apt: pkg={{ item }} state=present
  with_items:
   - openjdk-7-jdk
   - curl
   - logstash

- name: Enable logstash
  lineinfile: dest=/etc/default/logstash state=present insertafter=EOF
              regexp="^START="
              line="START=yes"
  notify: restart logstash

- name: Enable logstash-web
  lineinfile: dest=/etc/default/logstash-web state=present insertafter=EOF
              regexp="^START="
              line="START=yes"
  notify: restart logstash-web

- name: Create Logstash Indexer configuration
  template: src=logstash_indexer.conf.j2 dest="/etc/logstash/conf.d/indexer.conf" owner=root group=root mode=0644
  notify:
   - restart logstash

- name: Create Beaver user to allow receipt of logs in Redis via ssh
  user: name=beaver

- name: Allow the current user to ssh to the beaver user
  authorized_key: user=beaver key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Add Logstash user to the adm, redis and root groups so it can read the local logs
  user: name=logstash groups=adm,redis,root, append=yes
  notify:
   - restart logstash

- name: Start Logstash service
  service: name=logstash state=started enabled=true

- name: Start Logstash Web Interface service
  service: name=logstash-web state=started enabled=true
