---
# This playbook will install the latest rsyslog and configure TCP and/or UDP reception.

- name: Install rsyslog
  apt: pkg={{ item }} state=present
  with_items:
   - rsyslog

- name: Copy Rsyslog Conf
  template: src="reception.conf.j2" dest="/etc/rsyslog.d/90-reception.conf" owner=root group=root mode=0644
  notify:
   - restart rsyslog
